export const movieByCategoryData = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/fh022Zgyoq1UzxshTObNLjQ2JoC.jpg",
      genre_ids: [99],
      id: 1232289,
      original_language: "es",
      original_title: "La sociedad de la nieve: ¿Quiénes fuimos en la montaña?",
      overview:
        'An in-depth look at the creative process behind "Society of the Snow," featuring cast, crew, director J.A. Bayona and even real-life survivors.',
      popularity: 159.9,
      poster_path: "/6TGDsFSSi0dvpcwZsjUj6LxtPY2.jpg",
      release_date: "2024-01-23",
      title: "Society of the Snow: Who Were We on the Mountain?",
      video: false,
      vote_average: 7.773,
      vote_count: 11,
    },
    {
      adult: false,
      backdrop_path: "/5S31uyun3UTEHKOPtILe4i7VBAX.jpg",
      genre_ids: [99, 10402],
      id: 1226841,
      original_language: "en",
      original_title: "The Greatest Night in Pop",
      overview:
        "In 1985, 46 music icons, including Lionel Richie, Michael Jackson, Bruce Springsteen, Cyndi Lauper, Diana Ross, and Stevie Wonder, came together for the most star-studded recording session in history. This is the untold story of the legendary global pop song “We Are the World” — which very nearly didn’t happen.",
      popularity: 91.539,
      poster_path: "/jDz4wFujk94tQP9Sx6EMKDULvkn.jpg",
      release_date: "2024-01-19",
      title: "The Greatest Night in Pop",
      video: false,
      vote_average: 7.981,
      vote_count: 77,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 645488,
      original_language: "en",
      original_title: "Aquaman: Heroines of Atlantis",
      overview:
        "Amber Heard and Nicole Kidman discuss their characters Mera and Atlanna.",
      popularity: 85.205,
      poster_path: "/pa7m8nqDrEi7hAGB5vTnCkGLPC2.jpg",
      release_date: "2019-03-26",
      title: "Aquaman: Heroines of Atlantis",
      video: false,
      vote_average: 6.047,
      vote_count: 43,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 1206029,
      original_language: "es",
      original_title: "Muchachos, la película de la gente",
      overview:
        "The celebrations for the title of the Argentine National Team in the World Cup in Qatar 2022, through videos of Argentines around the world and unpublished material of the party in the streets.",
      popularity: 65.774,
      poster_path: "/ealnRH1fBYGfJVDaNseUe8K14Ge.jpg",
      release_date: "2023-12-07",
      title: "Muchachos, la película de la gente",
      video: false,
      vote_average: 6.75,
      vote_count: 8,
    },
    {
      adult: false,
      backdrop_path: "/wDSleqaukgwU8kILLrpP4Kf60eV.jpg",
      genre_ids: [99],
      id: 1192578,
      original_language: "es",
      original_title: "Elijo creer",
      overview:
        "It narrates the epic title obtained by the Argentine National Team in the World Cup Qatar 2022 with testimonies of the protagonists, told from the intimacy and in first person.",
      popularity: 59.926,
      poster_path: "/eLbDSu14EZ2VldIgDDGrt5pJkoL.jpg",
      release_date: "2023-12-07",
      title: "I Choose to Believe",
      video: false,
      vote_average: 7.379,
      vote_count: 58,
    },
    {
      adult: false,
      backdrop_path: "/8rft8A9nH43IReybFtYt21ezfMK.jpg",
      genre_ids: [99],
      id: 899082,
      original_language: "en",
      original_title: "Harry Potter 20th Anniversary: Return to Hogwarts",
      overview:
        "An enchanting making-of story told through all-new in-depth interviews and cast conversations, inviting fans on a magical first-person journey through one of the most beloved film franchises of all time.",
      popularity: 51.189,
      poster_path: "/jntLBq0MLR3hrwKaTQswxACRPMs.jpg",
      release_date: "2022-01-01",
      title: "Harry Potter 20th Anniversary: Return to Hogwarts",
      video: false,
      vote_average: 7.305,
      vote_count: 3156,
    },
    {
      adult: false,
      backdrop_path: "/pdZe9Sw5BKGDLrTWx7SmMAjpCgG.jpg",
      genre_ids: [99],
      id: 1232553,
      original_language: "en",
      original_title: "The Unbreakable Tatiana Suarez",
      overview:
        "Follow the exceptional spirit and drive of mixed martial arts (MMA) fighter Tatiana Suarez as she prepares to reenter the cage after nearly four years away from the sport. Suarez reflects on her journey from wrestling prodigy to professional athlete and the legacy she leaves young women, particularly those in the Latina community.",
      popularity: 48.448,
      poster_path: "/24iOlmQYV5aUgzLARyzSQN3T6qH.jpg",
      release_date: "2024-01-31",
      title: "The Unbreakable Tatiana Suarez",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/zfi4OFQXs2DC4zUOX8h3wbI948M.jpg",
      genre_ids: [80, 99],
      id: 1229958,
      original_language: "en",
      original_title: "Lover, Stalker, Killer",
      overview:
        "In this twisting documentary, a mechanic tries online dating for the first time and meets a woman who takes romantic obsession to a deadly extreme.",
      popularity: 44.747,
      poster_path: "/f5uojWzwJTCHBIV3rmGPTmQG7TF.jpg",
      release_date: "2024-02-09",
      title: "Lover, Stalker, Killer",
      video: false,
      vote_average: 8.5,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/10qHzowpyIpROMBAiUNGSdlTsFs.jpg",
      genre_ids: [99, 36],
      id: 21508,
      original_language: "es",
      original_title:
        "Stranded: I've Come from a Plane That Crashed on the Mountains",
      overview:
        "The story, told by the survivors, of a group of young men, members of a Uruguayan rugby team, who managed to survive for 72 days, at an altitude of almost 4,000 meters, in the heart of the Andes Mountains, after their plane, en route to Chile, crashed there on October 13, 1972.",
      popularity: 43.696,
      poster_path: "/3Uu9M1y36vI727Ec2oDMeS3V3Ys.jpg",
      release_date: "2008-10-22",
      title: "Stranded: I've Come from a Plane That Crashed on the Mountains",
      video: false,
      vote_average: 7.444,
      vote_count: 18,
    },
    {
      adult: false,
      backdrop_path: "/ifGs4hSnqTCFmhJqCGe5Ec0cTe5.jpg",
      genre_ids: [99],
      id: 1025169,
      original_language: "th",
      original_title: "13 หมูป่า: เรื่องเล่าจากในถ้ำ",
      overview:
        "In this compelling documentary, members of the Thai youth soccer team tell their stories of getting trapped in Tham Luang Cave in 2018 — and surviving.",
      popularity: 42.688,
      poster_path: "/jQb1UjOdc2DsU4SqDebrVH8dHvC.jpg",
      release_date: "2022-10-05",
      title: "The Trapped 13: How We Survived The Thai Cave",
      video: false,
      vote_average: 6.866,
      vote_count: 67,
    },
    {
      adult: false,
      backdrop_path: "/6eBB5Ejtn5TRWl9GYbRewo0oO4y.jpg",
      genre_ids: [99],
      id: 1004685,
      original_language: "en",
      original_title: "Nuclear Now",
      overview:
        "With unprecedented access to the nuclear industry in France, Russia, and the United States, Nuclear Now explores the possibility for the global community to overcome the challenges of climate change and energy poverty to reach a brighter future through the power of nuclear energy.  Beneath our feet, Uranium atoms in the Earth’s crust hold incredibly concentrated energy. Science unlocked this energy in the mid-20th century, first for bombs and then to power submarines. The United States led the effort to generate electricity from this new source. Yet in the mid-20th century as societies began the transition to nuclear power and away from fossil fuels, a long-term PR campaign to scare the public began, funded in part by coal and oil interests.",
      popularity: 41.405,
      poster_path: "/vdxG11NGlnDUWoSjRRkDKXh34ee.jpg",
      release_date: "2023-04-28",
      title: "Nuclear Now",
      video: false,
      vote_average: 7.444,
      vote_count: 9,
    },
    {
      adult: false,
      backdrop_path: "/3H8u03qr9se2pCv3QTHR1gxSa9k.jpg",
      genre_ids: [99, 28, 12],
      id: 1174725,
      original_language: "de",
      original_title: "Duell am Abgrund",
      overview:
        "Fearless alpine climbers Ueli Steck and Dani Arnold enter into a death-defying rivalry to set speed records on the Swiss Alps' great north faces.",
      popularity: 40.208,
      poster_path: "/tI9ybrWLiVLljLsNoqEjQF36oG4.jpg",
      release_date: "2023-10-04",
      title: "Race to the Summit",
      video: false,
      vote_average: 7.047,
      vote_count: 52,
    },
    {
      adult: false,
      backdrop_path: "/tU3mnpFLOAp2Ia6vHvGIw8ewJQb.jpg",
      genre_ids: [10402, 99],
      id: 1041513,
      original_language: "en",
      original_title: "Encanto at the Hollywood Bowl",
      overview:
        "A taped performance of the Encanto Live-to-Film Concert Experience at the Hollywood Bowl. The original cast puts on a miracle of a concert as they sing the favorite songs, accompanied by a full orchestra and 50 person ensemble, and the Hollywood Bowl transforms into Casita!",
      popularity: 37.994,
      poster_path: "/sa3Ku5yNVjp8NloWxJoI9dQjvOi.jpg",
      release_date: "2022-12-28",
      title: "Encanto at the Hollywood Bowl",
      video: false,
      vote_average: 7.079,
      vote_count: 152,
    },
    {
      adult: false,
      backdrop_path: "/oWpE71ORKX5HUZjeS6fM0gOScQ6.jpg",
      genre_ids: [99, 14],
      id: 413393,
      original_language: "en",
      original_title:
        "Pure Imagination: The Story of 'Willy Wonka \u0026 the Chocolate Factory'",
      overview:
        'Retrospective documentary on the making of the cult classic "Willy Wonka \u0026 the Chocolate Factory."',
      popularity: 36.33,
      poster_path: "/nxzZeGmE456c5ujVrkV2B42mmD4.jpg",
      release_date: "2001-11-13",
      title:
        "Pure Imagination: The Story of 'Willy Wonka \u0026 the Chocolate Factory'",
      video: false,
      vote_average: 6.833,
      vote_count: 17,
    },
    {
      adult: false,
      backdrop_path: "/2VFUh8spzyNbRNPyncIrFmSwBrd.jpg",
      genre_ids: [99],
      id: 438478,
      original_language: "fr",
      original_title: "Pornocratie: Les nouvelles multinationales du sexe",
      overview:
        "Never before have we watched as much porn as today yet the traditional porn industry is dying. The arrival of web sites showing amateur clips has transformed the way porn is made and consumed. Behind this transformation lies one opaque multinational.",
      popularity: 35.929,
      poster_path: "/kfa1KHSaewjv9sSrrHDdWNdroyv.jpg",
      release_date: "2017-03-12",
      title: "Pornocracy: The New Sex Multinationals",
      video: false,
      vote_average: 6.75,
      vote_count: 40,
    },
    {
      adult: false,
      backdrop_path: "/fmkZreRL3Orlp8YdbP4Z2pXm6BF.jpg",
      genre_ids: [35, 10749, 99],
      id: 1238166,
      original_language: "en",
      original_title: "Meet Me in Rome",
      overview:
        "Ready to risk it all for love, three women travel to Rome to become leading ladies in their very own reality rom-com. Daily script deliveries guide them to handsome suitors and magical destinations, where swoon-worthy dates and steamy romance await. But when challenged to push their fears aside, will our leading ladies find the love they are looking for, or will they leave as single as they came?",
      popularity: 35.244,
      poster_path: "/sJfkNahjiZD6iOPpu47AUAideyB.jpg",
      release_date: "2024-02-09",
      title: "Meet Me in Rome",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/eca3tlO1vtnua8LUK70ISDMYcwF.jpg",
      genre_ids: [99],
      id: 1146302,
      original_language: "en",
      original_title: "Sly",
      overview:
        "His love of film began as an escape from a rocky childhood. From underdog to Hollywood legend, Sylvester Stallone tells his story in this documentary.",
      popularity: 33.097,
      poster_path: "/1utWajLPvv1R9ZwkD98s2ZEngS.jpg",
      release_date: "2023-09-16",
      title: "Sly",
      video: false,
      vote_average: 7.24,
      vote_count: 125,
    },
    {
      adult: false,
      backdrop_path: "/fG5U8sQ2GHK4axzuLgH0bq8mddE.jpg",
      genre_ids: [99],
      id: 109520,
      original_language: "en",
      original_title: "After Porn Ends",
      overview:
        'Documentary examining what happens to some of the biggest names in the history of the adult entertainment industry after they leave the business and try and live "normal" lives.',
      popularity: 32.297,
      poster_path: "/aPerSjt4viv7Ik8OEHL83AbrH6R.jpg",
      release_date: "2012-05-21",
      title: "After Porn Ends",
      video: false,
      vote_average: 5.677,
      vote_count: 253,
    },
    {
      adult: false,
      backdrop_path: "/sGE6N1vJjxZLkOJEXdIOqTslxuL.jpg",
      genre_ids: [99],
      id: 1087040,
      original_language: "en",
      original_title: "Money Shot: The Pornhub Story",
      overview:
        "Featuring interviews with performers, activists and past employees, this documentary offers a deep dive into the successes and scandals of Pornhub.",
      popularity: 31.425,
      poster_path: "/kpTqWqLYcf1uErnx5VXLah4EWJZ.jpg",
      release_date: "2023-03-15",
      title: "Money Shot: The Pornhub Story",
      video: false,
      vote_average: 5.659,
      vote_count: 267,
    },
    {
      adult: false,
      backdrop_path: "/ji6MRyevgzCtrtxAvKotzhagOOJ.jpg",
      genre_ids: [99],
      id: 1235525,
      original_language: "en",
      original_title: "Marvel Studios Assembled: The Making of The Marvels",
      overview:
        'Take an intergalactic trip with the cast and crew of "The Marvels" as they tell their experiences making this weird and wonderful film. Step into all the departments of production and discover how they created complex fight scenes, countless alien life forms, and some of the most elaborate sets ever. From dance parties to kitten days, the cast and crew had an unforgettable time making the movie.',
      popularity: 30.702,
      poster_path: "/9sFICxo3xVJRbTCwvLwGbOShJGP.jpg",
      release_date: "2024-02-07",
      title: "Marvel Studios Assembled: The Making of The Marvels",
      video: false,
      vote_average: 4.8,
      vote_count: 3,
    },
  ],
  total_pages: 7391,
  total_results: 147811,
};

export const movieData = {
  adult: false,
  backdrop_path: "/yyFc8Iclt2jxPmLztbP617xXllT.jpg",
  belongs_to_collection: null,
  budget: 125000000,
  genres: [
    {
      id: 35,
      name: "Comedy",
    },
    {
      id: 10751,
      name: "Family",
    },
    {
      id: 14,
      name: "Fantasy",
    },
  ],
  homepage: "https://www.wonkamovie.com",
  id: 787699,
  imdb_id: "tt6166392",
  original_language: "en",
  original_title: "Wonka",
  overview:
    "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
  popularity: 1303.308,
  poster_path: "/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
  production_companies: [
    {
      id: 174,
      logo_path: "/zhD3hhtKB5qyv7ZeL4uLpNxgMVU.png",
      name: "Warner Bros. Pictures",
      origin_country: "US",
    },
    {
      id: 79,
      logo_path: "/at4uYdwAAgNRKhZuuFX8ShKSybw.png",
      name: "Village Roadshow Pictures",
      origin_country: "US",
    },
    {
      id: 214904,
      logo_path: "/9S6xSAsUiE1zuKzxayco7fD0p26.png",
      name: "The Roald Dahl Story Company",
      origin_country: "GB",
    },
    {
      id: 437,
      logo_path: "/nu20mtwbEIhUNnQ5NXVhHsNknZj.png",
      name: "Heyday Films",
      origin_country: "GB",
    },
    {
      id: 216687,
      logo_path: null,
      name: "Domain Entertainment",
      origin_country: "US",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "GB",
      name: "United Kingdom",
    },
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  release_date: "2023-12-06",
  revenue: 572668328,
  runtime: 117,
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
  ],
  status: "Released",
  tagline: "Every good thing in this world started with a dream.",
  title: "Wonka",
  video: false,
  vote_average: 7.211,
  vote_count: 1974,
};

export const popularData = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg",
      genre_ids: [28, 53, 18],
      id: 866398,
      original_language: "en",
      original_title: "The Beekeeper",
      overview:
        "One man’s campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
      popularity: 2265.436,
      poster_path: "/A7EByudX0eOzlkQ2FIbogzyazm2.jpg",
      release_date: "2024-01-10",
      title: "The Beekeeper",
      video: false,
      vote_average: 7.268,
      vote_count: 906,
    },
    {
      adult: false,
      backdrop_path: "/pWsD91G2R1Da3AKM3ymr3UoIfRb.jpg",
      genre_ids: [28, 878, 18],
      id: 933131,
      original_language: "ko",
      original_title: "황야",
      overview:
        "After a deadly earthquake turns Seoul into a lawless badland, a fearless huntsman springs into action to rescue a teenager abducted by a mad doctor.",
      popularity: 2428.936,
      poster_path: "/zVMyvNowgbsBAL6O6esWfRpAcOb.jpg",
      release_date: "2024-01-26",
      title: "Badland Hunters",
      video: false,
      vote_average: 6.815,
      vote_count: 252,
    },
    {
      adult: false,
      backdrop_path: "/criPrxkTggCra1jch49jsiSeXo1.jpg",
      genre_ids: [878, 12, 28],
      id: 609681,
      original_language: "en",
      original_title: "The Marvels",
      overview:
        "Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.",
      popularity: 1287.814,
      poster_path: "/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
      release_date: "2023-11-08",
      title: "The Marvels",
      video: false,
      vote_average: 6.3,
      vote_count: 1503,
    },
    {
      adult: false,
      backdrop_path: "/yyFc8Iclt2jxPmLztbP617xXllT.jpg",
      genre_ids: [35, 10751, 14],
      id: 787699,
      original_language: "en",
      original_title: "Wonka",
      overview:
        "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
      popularity: 1303.308,
      poster_path: "/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
      release_date: "2023-12-06",
      title: "Wonka",
      video: false,
      vote_average: 7.211,
      vote_count: 1973,
    },
    {
      adult: false,
      backdrop_path: "/cnqwv5Uz3UW5f086IWbQKr3ksJr.jpg",
      genre_ids: [28, 12, 14],
      id: 572802,
      original_language: "en",
      original_title: "Aquaman and the Lost Kingdom",
      overview:
        "Black Manta seeks revenge on Aquaman for his father's death. Wielding the Black Trident's power, he becomes a formidable foe. To defend Atlantis, Aquaman forges an alliance with his imprisoned brother. They must protect the kingdom.",
      popularity: 970.392,
      poster_path: "/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg",
      release_date: "2023-12-20",
      title: "Aquaman and the Lost Kingdom",
      video: false,
      vote_average: 6.934,
      vote_count: 1522,
    },
    {
      adult: false,
      backdrop_path: "/meyhnvssZOPPjud4F1CjOb4snET.jpg",
      genre_ids: [16, 28, 12, 35, 10751],
      id: 940551,
      original_language: "en",
      original_title: "Migration",
      overview:
        "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
      popularity: 961.294,
      poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
      release_date: "2023-12-06",
      title: "Migration",
      video: false,
      vote_average: 7.647,
      vote_count: 568,
    },
    {
      adult: false,
      backdrop_path: "/unvtbkgxh47BewQ8pENvdOdme0r.jpg",
      genre_ids: [28, 18],
      id: 1212073,
      original_language: "de",
      original_title: "60 Minuten",
      overview:
        "Desperate to keep custody of his daughter, a mixed martial arts fighter abandons a big match and races across Berlin to attend her birthday party.",
      popularity: 1346.069,
      poster_path: "/jojfbnIHGsRpodIood3OQoqA45Y.jpg",
      release_date: "2024-01-19",
      title: "Sixty Minutes",
      video: false,
      vote_average: 6.996,
      vote_count: 238,
    },
    {
      adult: false,
      backdrop_path: "/ehumsuIBbgAe1hg343oszCLrAfI.jpg",
      genre_ids: [16, 10751, 14, 12],
      id: 1022796,
      original_language: "en",
      original_title: "Wish",
      overview:
        "Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.",
      popularity: 944.601,
      poster_path: "/AcoVfiv1rrWOmAdpnAMnM56ki19.jpg",
      release_date: "2023-11-13",
      title: "Wish",
      video: false,
      vote_average: 6.653,
      vote_count: 670,
    },
    {
      adult: false,
      backdrop_path: "/y9Dr6yCVYRmjKuDjOjNyWxVuGjp.jpg",
      genre_ids: [80, 28],
      id: 370464,
      original_language: "en",
      original_title: "The Masked Saint",
      overview:
        "The journey of a professional wrestler who becomes a small town pastor and moonlights as a masked vigilante fighting injustice. While facing crises at home and at the church, the Pastor must evade the police and somehow reconcile his violent secret identity with his calling as a pastor.",
      popularity: 467.063,
      poster_path: "/zlT1Tc9hA1Ntye5hr7Gxos9U6U9.jpg",
      release_date: "2016-01-08",
      title: "The Masked Saint",
      video: false,
      vote_average: 4.155,
      vote_count: 29,
    },
    {
      adult: false,
      backdrop_path: "/1BFLsVxE1NzCIwicfOPtzzB4Kxh.jpg",
      genre_ids: [80, 53, 28],
      id: 982940,
      original_language: "en",
      original_title: "Due Justice",
      overview:
        "An attorney with a military past hunts down the gang who killed his wife and took his daughter.",
      popularity: 592.782,
      poster_path: "/35Uef7fz9ctYbJLXbJBCqvtttEQ.jpg",
      release_date: "2023-11-24",
      title: "Due Justice",
      video: false,
      vote_average: 6.778,
      vote_count: 27,
    },
    {
      adult: false,
      backdrop_path: "/zLj0peaxy5y2SlC6wNIQ4V0pfqg.jpg",
      genre_ids: [16, 10751, 35, 14],
      id: 1139829,
      original_language: "en",
      original_title: "Orion and the Dark",
      overview:
        "A boy with an active imagination faces his fears on an unforgettable journey through the night with his new friend: a giant, smiling creature named Dark.",
      popularity: 836.851,
      poster_path: "/uHiXFLMlnl5jBjtfOliapN16yBD.jpg",
      release_date: "2024-02-02",
      title: "Orion and the Dark",
      video: false,
      vote_average: 6.795,
      vote_count: 122,
    },
    {
      adult: false,
      backdrop_path: "/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg",
      genre_ids: [35, 10749],
      id: 1072790,
      original_language: "en",
      original_title: "Anyone But You",
      overview:
        "Bea and Ben look like the perfect couple, but after an amazing first date something happens that turns their fiery hot attraction ice cold - until they find themselves unexpectedly thrust together at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
      popularity: 725.952,
      poster_path: "/yRt7MGBElkLQOYRvLTT1b3B1rcp.jpg",
      release_date: "2023-12-21",
      title: "Anyone But You",
      video: false,
      vote_average: 7.2,
      vote_count: 272,
    },
    {
      adult: false,
      backdrop_path: "/zUY1WawCBY8y6YBoiUCAmUorXfx.jpg",
      genre_ids: [14, 28, 12],
      id: 528656,
      original_language: "zh",
      original_title: "战神纪",
      overview:
        "Temüjin and Börte are childhood lovers who are deeply in love; but news of Temüjin's father's death swiftly disrupted their relationship. Temüjin heads back to his hometown, but was faced with a sudden attack from his father's former comrades, causing his whole tribe to be destroyed.",
      popularity: 424.684,
      poster_path: "/FgFoX4wlZUT31ErGGzVnNlh8U3.jpg",
      release_date: "2018-04-28",
      title: "Genghis Khan",
      video: false,
      vote_average: 5.35,
      vote_count: 10,
    },
    {
      adult: false,
      backdrop_path: "/rz8GGX5Id2hCW1KzAIY4xwbQw1w.jpg",
      genre_ids: [28, 35, 80],
      id: 955916,
      original_language: "en",
      original_title: "Lift",
      overview:
        "An international heist crew, led by Cyrus Whitaker, race to lift $500 million in gold from a passenger plane at 40,000 feet.",
      popularity: 926.968,
      poster_path: "/46sp1Z9b2PPTgCMyA87g9aTLUXi.jpg",
      release_date: "2024-01-10",
      title: "Lift",
      video: false,
      vote_average: 6.581,
      vote_count: 712,
    },
    {
      adult: false,
      backdrop_path: "/ba9TgAO4I8RyA2LljzR3MspHaM9.jpg",
      genre_ids: [28, 878, 53],
      id: 799155,
      original_language: "hi",
      original_title: "Attack",
      overview:
        "With the Parliament under siege, India’s first super soldier Arjun Shergill is tasked to get hold of the terrorists in the nick of time, save the Prime Minister from their clutches and stop a dirty bomb from exploding and destroying Delhi. Will Arjun succeed in his mission?",
      popularity: 379.451,
      poster_path: "/5jGKbYuZtdxSNOocI6ZziQeiY4n.jpg",
      release_date: "2022-04-01",
      title: "Attack",
      video: false,
      vote_average: 7.346,
      vote_count: 120,
    },
    {
      adult: false,
      backdrop_path: "/f1AQhx6ZfGhPZFTVKgxG91PhEYc.jpg",
      genre_ids: [36, 10752, 28, 18],
      id: 753342,
      original_language: "en",
      original_title: "Napoleon",
      overview:
        "An epic that details the checkered rise and fall of French Emperor Napoleon Bonaparte and his relentless journey to power through the prism of his addictive, volatile relationship with his wife, Josephine.",
      popularity: 652.558,
      poster_path: "/vcZWJGvB5xydWuUO1vaTLI82tGi.jpg",
      release_date: "2023-11-22",
      title: "Napoleon",
      video: false,
      vote_average: 6.526,
      vote_count: 1624,
    },
    {
      adult: false,
      backdrop_path: "/tlNzm03CHTNEXc1mih0obFBYwwx.jpg",
      genre_ids: [878, 28],
      id: 1028725,
      original_language: "zh",
      original_title: "变种人：幽灵战姬",
      overview:
        "Wu Qingqing is an agent of the International Security Alliance (to combat mutant crime) and is ordered to infiltrate Medusa Plastic Hospital to collect evidence of the secret research on genetic induction fluid by its direct consortium to create mutant fighters. Wu Qingqing successfully infiltrates, but was forced to inject a gene induction fluid.",
      popularity: 371.219,
      poster_path: "/ensNfCsxIRIr6LJnrRCXd94tfd.jpg",
      release_date: "2022-09-26",
      title: "Mutant: Ghost War Girl",
      video: false,
      vote_average: 5.211,
      vote_count: 19,
    },
    {
      adult: false,
      backdrop_path: "/yl2GfeCaPoxChcGyM5p7vYp1CKS.jpg",
      genre_ids: [28, 35, 10749],
      id: 848187,
      original_language: "en",
      original_title: "Role Play",
      overview:
        "Emma has a wonderful husband and two kids in the suburbs of New Jersey – she also has a secret life as an assassin for hire – a secret that her husband David discovers when the couple decide to spice up their marriage with a little role play.",
      popularity: 611.977,
      poster_path: "/7MhXiTmTl16LwXNPbWCmqxj7UxH.jpg",
      release_date: "2024-01-04",
      title: "Role Play",
      video: false,
      vote_average: 6.036,
      vote_count: 292,
    },
    {
      adult: false,
      backdrop_path: "/acpFrSmVLnTNAIuHxnZArkC3dwU.jpg",
      genre_ids: [16, 28, 12, 10751, 14],
      id: 598387,
      original_language: "en",
      original_title: "The Tiger's Apprentice",
      overview:
        "After the death of his grandmother, Tom Lee discovers he is part of a long lineage of magical protectors known as the Guardians. With guidance from a mythical tiger named Hu and the other Zodiac animal warriors, Tom trains to take on an evil force that threatens humanity.",
      popularity: 598.595,
      poster_path: "/iiid1xMhoAcW83VJ9LdAqf4Vtbr.jpg",
      release_date: "2024-02-02",
      title: "The Tiger's Apprentice",
      video: false,
      vote_average: 7.0,
      vote_count: 31,
    },
    {
      adult: false,
      backdrop_path: "/jkBFGhuJKLH8VurXqVKQ2mxvVYC.jpg",
      genre_ids: [37],
      id: 1079394,
      original_language: "en",
      original_title: "The Five",
      overview:
        "A scorned woman enlist the help of five strangers to execute a bank robbery. Tensions rise as the men anxiously await her arrival with the money, leaving the crew to wonder if they have been betrayed.",
      popularity: 348.163,
      poster_path: "/xckDPGprPVDpuzhSyo9E7SZJ2wa.jpg",
      release_date: "2023-01-07",
      title: "The Five",
      video: false,
      vote_average: 7.059,
      vote_count: 17,
    },
  ],
  total_pages: 42399,
  total_results: 847973,
};
export const categoriesData = {
  genres: [
    {
      id: 28,
      name: "Action",
    },
    {
      id: 12,
      name: "Adventure",
    },
    {
      id: 16,
      name: "Animation",
    },
    {
      id: 35,
      name: "Comedy",
    },
    {
      id: 80,
      name: "Crime",
    },
    {
      id: 99,
      name: "Documentary",
    },
    {
      id: 18,
      name: "Drama",
    },
    {
      id: 10751,
      name: "Family",
    },
    {
      id: 14,
      name: "Fantasy",
    },
    {
      id: 36,
      name: "History",
    },
    {
      id: 27,
      name: "Horror",
    },
    {
      id: 10402,
      name: "Music",
    },
    {
      id: 9648,
      name: "Mystery",
    },
    {
      id: 10749,
      name: "Romance",
    },
    {
      id: 878,
      name: "Science Fiction",
    },
    {
      id: 10770,
      name: "TV Movie",
    },
    {
      id: 53,
      name: "Thriller",
    },
    {
      id: 10752,
      name: "War",
    },
    {
      id: 37,
      name: "Western",
    },
  ],
};
